theme: jekyll-theme-slate
title: Welcome to the RC home page!
description: I thought I was listing new changes to make to my RC project and learning the GitHub workflow, but now I have no idea what is going on...
